services:
  app:
   image: aveein/laravel-docker-v2
   container_name: laravel
   ports:
       - "8080:8000"
   command: php artisan serve --host=0.0.0.0 --port=8000
#    volumes:
#       - ./src:/var/www/
#       - ./src/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
   networks:
      - app-network
  db:
    image: mysql
    container_name: db
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
